
export interface ConfigurationTypes {
  id: number;
  type_register: number;
  type_artist: number;
  name: string;
  email: string;
  phone: string | null;
  site: string | null;
  centralfa: string | null;
  mode: string | null;
  product: string | null;
  token_agendaoficial: string | null;
  token_xpshows: string | null;
  token_artiz: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  client_id: number;
  l8driver: string | null;
  company: boolean;
  musical_styles_id: number | null;
  uuid: string;
  store_link: string | null;
  migration_id: string | null;
  color: string | null;
  image: string | null;
  image_medium: string | null;
  image_small: string | null;
  language: string;
  produced_by: string | null;
  whatsapp_endpoint: string | null;
  whatsapp_client: string | null;
  whatsapp_secret: string | null;
  configurations: PlataformsIdTypes[];
  basic_configurations: SocialType[];
  site_configuration_people: ThemeTypes[];
  menus: MenusType[];

}

export interface PlataformsIdTypes {

  id: number;
  person_id: number;
  signature: string | null;
  photo: string | null;
  flickrid?: string | null;
  flickralbum?: string | null;
  youtubeidplaylist: string | null;
  youtubeidcanal: string | null;
  spotifyid: string | null;
  deezerid: string | null;
  twittername: string | null;
  twitterhashtag: string | null;
  accountgoogleservice: string | null;
  analyticsviewid: string | null;
  analytics_metric: string | null;
  facebookpixel: string | null;
  hostftp: string | null;
  userftp: string | null;
  passwordftp: string | null;
  tagmanager: string | null;
  komposer: string | null;
  created_at: string;
  updated_at: string;
  language: string;

}

export interface ThemeTypes {
  color_text_01: string | null;
  color_text_02: string | null;
  color_text_03: string | null;
  color_text_04: string | null;
  color_text_05: string | null;
  color_back_01: string | null;
  color_back_02: string | null;
  color_back_03: string | null;
  color_back_04: string | null;
  color_back_05: string | null;
  color_alert_01: string | null;
  signature_back: string | null;
  signature_text: string | null;
  bgdesk_home: string | null;
  bgdesk_calendar: string | null;
  bgdesk_biography: string | null;
  bgdesk_music: string | null;
  bgdesk_social: string | null;
  bgdesk_video: string | null;
  bgdesk_photo: string | null;
  bgdesk_notice: string | null;
  bgdesk_notice_detail: string | null;
  bgdesk_areafa: string | null;
  bgdesk_contact: string | null;
  bgdesk_parallax_01: string | null;
  bgdesk_parallax_02: string | null;
  bgdesk_store: string | null;
  bgdesk_history: string | null;
  bgvideo_desk_cdn: string ;
  // Backgrounds mobile
  bgmobile_home: string | null;
  bgmobile_calendar: string | null;
  bgmobile_biography: string | null;
  bgmobile_music: string | null;
  bgmobile_social: string | null;
  bgmobile_video: string | null;
  bgmobile_photo: string | null;
  bgmobile_notice: string | null;
  bgmobile_notice_detail: string | null;
  bgmobile_areafa: string | null;
  bgmobile_contact: string | null;
  bgmobile_store: string | null;
  bgmobile_history: string | null;
  color_rgb_text_01: string;
  color_rgb_text_02: string;
  color_rgb_text_03: string;
  color_rgb_text_04: string;
  color_rgb_text_05: string;
  color_rgb_back_01: string;
  color_rgb_back_02: string;
  color_rgb_back_03: string;
  color_rgb_back_04: string;
  color_rgb_back_05: string;
  color_rgb_alert_01: string;
  signature_rgb_back: string | null;
  signature_rgb_text: string | null;
  bgvideo_desk: string | null;
  bgvideo_mobile: string | null;
  bgdesk_home_cdn: string;
  bgdesk_calendar_cdn: string;
  bgdesk_biography_cdn: string;
  bgdesk_music_cdn: string;
  bgdesk_social_cdn: string;
  bgdesk_video_cdn: string;
  bgdesk_photo_cdn: string;
  bgdesk_notice_cdn: string;
  bgdesk_notice_detail_cdn: string;
  bgdesk_areafa_cdn: string;
  bgdesk_contact_cdn: string;
  bgdesk_parallax_01_cdn: string;
  bgdesk_parallax_02_cdn: string;
  bgdesk_store_cdn: string;
  bgdesk_history_cdn: string;
  bgvideo_mobile_cdn: string;
  bgmobile_home_cdn: string;
  bgmobile_calendar_cdn: string;
  bgmobile_biography_cdn: string;
  bgmobile_music_cdn: string;
  bgmobile_social_cdn: string;
  bgmobile_video_cdn: string;
  bgmobile_photo_cdn: string;
  bgmobile_notice_cdn: string;
  bgmobile_notice_detail_cdn: string;
  bgmobile_areafa_cdn: string;
  bgmobile_contact_cdn: string;
  bgmobile_store_cdn: string;
  bgmobile_history_cdn: string;
  language: string;
}

export interface MenusType {
  menus: [];
}
export interface SocialType {
  id: number;
  person_id: number;
  logo: string | null;
  white_logo: string | null;
  favicon: string | null;
  whatsapp_number: string | null;
  phone1: string | null;
  phone2: string | null;
  email: string | null;
  facebook: string | null;
  instagram: string | null;
  tiktok: string | null;
  twitter: string | null;
  flickr: string | null;
  youtube: string | null;
  spotify: string | null;
  threads: string | null;
  linkedin: string | null;
  address: string | null;
  latitude: string | null;
  longitude: string | null;
  meta_title: string;
  meta_image: string | null;
  meta_description?: string;
  meta_keywords: string | null;
  link_music: string | null;
  link_deezer: string | null;
  link_tidal: string | null;
  link_napster: string | null;
  link_itunes: string | null;
  link_googleplay: string | null;
  link_superplayer: string | null;
  link_vagalume: string | null;
  link_youtube_music: string | null;
  link_palcomp3: string | null;
  link_suamusica: string | null;
  amazon_music: string | null;
  banner_email: string | null;
  logo_cdn: string | null;
  white_logo_cdn: string | null;
  favicon_cdn: string | null;
  meta_image_cdn: string;
  banner_email_cdn: string | null;
  cdn: boolean;
  language: string;
  created_at: string;
  updated_at: string;
  basic_configurations: SiteSettings[] | null;
}

export interface SiteSettings {
  person_id: string | number;
  logo: string | null;
  white_logo: string | null;
  favicon: string | null;
  whatsapp_number: string | null;
  phone1: string | null;
  phone2: string | null;
  email: string | null;
  facebook: string | null;
  instagram: string | null;
  tiktok: string | null;
  twitter: string | null;
  flickr: string | null;
  youtube: string | null;
  spotify: string | null;
  address: string | null;
  latitude: string | null;
  longitude: string | null;
  meta_title: string | null;
  meta_image: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  link_music: string | null;
  link_deezer: string | null;
  link_tidal: string | null;
  link_napster: string | null;
  link_itunes: string | null;
  link_googleplay: string | null;
  link_superplayer: string | null;
  link_vagalume: string | null;
  link_youtube_music: string | null;
  link_palcomp3: string | null;
  link_suamusica: string | null;
  cdn: string | null;
  banner_email: string | null;
  logo_cdn: string | null;
  white_logo_cdn: string | null;
  favicon_cdn: string | null;
  meta_image_cdn: string | null;
  banner_email_cdn: string | null;
}
